New files Added
Karthi0505/fita_batch1_youtube_api pull request #8
Opened 2024-04-12 02:39 UTC by Priyanka250602

Navbar file added

2024-04-12 03:54 UTC, Karthi0505 requested changes

2024-04-12 03:54 UTC, Karthi0505 commented on src/App.js
> +import {BrowserRouter,Routes,Route}from 'react-dom'
Wrong package

2024-04-15 03:27 UTC, Karthi0505 approved these changes

2024-04-15 03:29 UTC, Priyanka250602 commented on src/App.js
> +import {BrowserRouter,Routes,Route}from 'react-dom'
changes done sir

2024-04-16 03:24 UTC, purni98n approved these changes

2024-04-16 03:48 UTC, DhanushaRenganathan approved these changes

2024-04-16 03:48 UTC, DhanushaRenganathan approved these changes

2024-04-16 03:57 UTC, purni98n approved these changes

2024-04-16 11:02 UTC, merged